In [1]:
# 1 Create a 6x6 NumPy array with random integers (0-255) to simulate a grayscale image, then apply a 2x2 max pooling operation with a stride of 2 and print the resulting reduced array.

import numpy as np

img = np.random.randint(0, 256, (6, 6))

# 2x2 Max Pooling (stride = 2)
pooled = img.reshape(3, 2, 3, 2).max(axis=(1, 3))

print("Original Image:\n", img)
print("\nAfter Max Pooling:\n", pooled)

Original Image:
 [[ 44 246 107 188 150  91]
 [ 39 121 100  71  17 198]
 [  1 164  50 186 103  62]
 [243 232   3 162  30 184]
 [  2  32  34 104  43  34]
 [219  69  47 168 118  24]]

After Max Pooling:
 [[246 188 198]
 [243 186 184]
 [219 168 118]]


In [2]:
# 2 Write a Python function average_pooling_2x2(image) that takes a 2D NumPy array and returns a new array after applying 2x2 average pooling with stride 2.

import numpy as np

def average_pooling_2x2(image):
    h, w = image.shape
    return image.reshape(h//2, 2, w//2, 2).mean(axis=(1, 3))

# Example
img = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12],
    [13,14,15,16]
])

print(average_pooling_2x2(img))

[[ 3.5  5.5]
 [11.5 13.5]]


In [ ]:
# 3 Given a 4x4 feature map array, manually perform both max pooling and average pooling with a 2x2 window and stride 2, and compare the results side by side.<br><br><em><strong>Hint:</strong> Show both resulting arrays and explain in one line which pooling method keeps more details from the original image.</em>

import numpy as np

# 4x4 feature map
feature_map = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 8, 3, 1],
    [0, 2, 9, 4]
])
# Max Pooling
max_pool = np.array([
    [np.max(feature_map[0:2, 0:2]), np.max(feature_map[0:2, 2:4])],
    [np.max(feature_map[2:4, 0:2]), np.max(feature_map[2:4, 2:4])]
])
# Average Pooling
avg_pool = np.array([
    [np.mean(feature_map[0:2, 0:2]), np.mean(feature_map[0:2, 2:4])],
    [np.mean(feature_map[2:4, 0:2]), np.mean(feature_map[2:4, 2:4])]
])
print("Max Pooling:\n", max_pool)
print("\nAverage Pooling:\n", avg_pool)

Max Pooling:
 [[6 4]
 [8 9]]

Average Pooling:
 [[3.75 2.25]
 [4.25 4.25]]


In [4]:
# 4 Combine a single 3x3 convolution layer (use any simple filter, e.g., edge detection) followed by a 2x2 max pooling layer on a 5x5 input array. Show the output after each step.

import numpy as np

# 5x5 input
img = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 0],
    [7, 8, 9, 2, 1],
    [1, 2, 3, 4, 5],
    [0, 1, 2, 3, 4]
])
# 3x3 Edge Detection Filter
kernel = np.array([
    [ 1, 0, -1],
    [ 1, 0, -1],
    [ 1, 0, -1]
])

# Convolution Output (3x3)
conv = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        conv[i,j] = np.sum(img[i:i+3, j:j+3] * kernel)

print("After Convolution:\n", conv)
# 2x2 Max Pooling (stride=2)
pool = np.array([[np.max(conv[0:2, 0:2])]])
print("\nAfter Max Pooling:\n", pool)

After Convolution:
 [[-6. 12. 16.]
 [-6.  8. 12.]
 [-6.  2.  4.]]

After Max Pooling:
 [[12.]]


5 Explain in your own words, using an example from Instagram or Zomato, how pooling layers help reduce computation and improve feature extraction in deep learning models.

Instagram Example:
When Instagram analyzes a photo to recognize a face, the image may contain millions of pixels. A pooling layer reduces the size of the feature maps by keeping only the most important information (such as strong facial features like eyes, nose, and mouth). This reduces computation and makes the model faster while still preserving the key features needed for recognition.

Zomato Example:
When a user uploads a food image, pooling helps reduce the image data while retaining important features such as the shape, texture, and edges of the food. As a result, the model can identify items like pizza or burgers more efficiently, even if the image is large or the food appears in slightly different positions.