In [1]:
# 1 Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel) and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.

import numpy as np

img = np.random.randint(0, 10, (5, 5))

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

out = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        out[i, j] = np.sum(img[i:i+3, j:j+3] * kernel)

print("Image:\n", img)
print("\nActivation Map:\n", out)

Image:
 [[7 3 3 3 4]
 [9 7 8 5 1]
 [2 2 2 6 0]
 [3 9 2 4 2]
 [4 2 3 3 8]]

Activation Map:
 [[ 5. -2.  8.]
 [ 2.  3.  9.]
 [ 2.  0. -3.]]


In [2]:
# 2 Implement a Python function apply_stride_convolution(input_matrix, kernel, stride) that performs convolution with a given stride on a 6x6 matrix and a 3x3 kernel, returning the resulting activation map.<br><br><em><strong>Hint:</strong> Use nested loops to move the kernel by the stride value over the input matrix.</em>

from numpy.lib.stride_tricks import sliding_window_view

def apply_stride_convolution(img, kernel, stride):
    windows = sliding_window_view(img, (3, 3))[::stride, ::stride]
    return np.sum(windows * kernel, axis=(2, 3))

# Example
img = np.random.randint(0, 10, (6, 6))
kernel = np.ones((3, 3))

print(apply_stride_convolution(img, kernel, 2))

[[49. 49.]
 [43. 41.]]


In [3]:
# 3 Modify your convolution code to add zero-padding of 1 around the input matrix before applying the convolution, and show the new activation map output.

import numpy as np
img = np.random.randint(0, 10, (5, 5))

# 3x3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Add zero-padding of 1
padded = np.pad(img, pad_width=1, mode='constant')

# Convolution
out = np.zeros((5, 5))

for i in range(5):
    for j in range(5):
        out[i, j] = np.sum(padded[i:i+3, j:j+3] * kernel)

print("Input:\n", img)
print("\nPadded Input:\n", padded)
print("\nActivation Map:\n", out)

Input:
 [[0 0 4 9 4]
 [1 1 6 2 3]
 [0 1 1 5 2]
 [5 3 1 1 1]
 [0 0 3 1 7]]

Padded Input:
 [[0 0 0 0 0 0 0]
 [0 0 0 4 9 4 0]
 [0 1 1 6 2 3 0]
 [0 0 1 1 5 2 0]
 [0 5 3 1 1 1 0]
 [0 0 0 3 1 7 0]
 [0 0 0 0 0 0 0]]

Activation Map:
 [[ -1.  -9. -10.   3.  11.]
 [ -2. -10. -14.   2.  16.]
 [ -5.  -2.  -3.   2.   8.]
 [ -4.   0.  -3.  -5.   7.]
 [ -3.   1.   1.  -4.   2.]]


In [4]:
# 4 Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel or Laplacian kernel for edge detection and an averaging kernel for blur.</em>

import numpy as np

img = np.array([
    [1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [1, 2, 3, 4, 5],
    [5, 4, 3, 2, 1],
    [1, 2, 3, 4, 5]
])

edge = np.array([
    [-1, -1, -1],
    [-1,  8, -1],
    [-1, -1, -1]
])

blur = np.ones((3,3)) / 9

edge_map = np.zeros((3,3))
blur_map = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        block = img[i:i+3, j:j+3]
        edge_map[i,j] = np.sum(block * edge)
        blur_map[i,j] = np.sum(block * blur)

print("Edge Detection:\n", edge_map)
print("\nBlur:\n", blur_map)

Edge Detection:
 [[ 12.   0. -12.]
 [-12.   0.  12.]
 [ 12.   0. -12.]]

Blur:
 [[2.66666667 3.         3.33333333]
 [3.33333333 3.         2.66666667]
 [2.66666667 3.         3.33333333]]


In [5]:
# 5 Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice. Show the input and output arrays and briefly describe what feature your filter detects.

from PIL import Image
import numpy as np

# Load image, convert to grayscale, resize to 8x8
img = Image.open("image.avif").convert("L").resize((8, 8))
img = np.array(img)

# Vertical edge detection filter
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Convolution
output = np.zeros((6, 6))

for i in range(6):
    for j in range(6):
        output[i, j] = np.sum(img[i:i+3, j:j+3] * kernel)

print("Input Array:\n", img)
print("\nOutput Array:\n", output)

Input Array:
 [[ 42  81  83  50  50  49  41  43]
 [ 47  86  73  50  62  55  40  61]
 [ 84 107  54  49 108 129  48  50]
 [ 85 133  69  95 132 108  59  62]
 [101 131  73  93  88  65  61 112]
 [ 89 126 129 125  79  54 127 114]
 [ 68  70  96 143  68  56  75  53]
 [ 52  40  77 138  62  64  95  42]]

Output Array:
 [[ -37.  125.  -10.  -84.   91.   79.]
 [  20.  132. -106.  -98.  155.  119.]
 [  74.  134. -132.  -65.  160.   78.]
 [   4.   77.  -28.   86.   52.  -61.]
 [ -40.  -34.   63.  186.  -28. -104.]
 [ -93. -170.   93.  232.  -88.  -35.]]
