In [1]:
# 1 Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.

import numpy as np

ratings = np.array([
    [5, 4, 3, 5, 4],  
    [4, 5, 4, 3, 5],  
    [3, 4, 5, 4, 4],  
    [5, 3, 4, 5, 5]   
])

print("All Ratings:")
print(ratings)
selected_users = ratings[1:3, :]
print("\nRatings of Second and Third Users:")
print(selected_users)



All Ratings:
[[5 4 3 5 4]
 [4 5 4 3 5]
 [3 4 5 4 4]
 [5 3 4 5 5]]

Ratings of Second and Third Users:
[[4 5 4 3 5]
 [3 4 5 4 4]]


In [2]:
# 2 Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>

steps = np.array([7500, 8200, 9000, 6800, 10000, 7800, 8500, 9200, 7000, 11000])
high_steps = steps[steps > 8000]
print("All Steps:", steps)
print("Steps Greater Than 8000:", high_steps)

All Steps: [ 7500  8200  9000  6800 10000  7800  8500  9200  7000 11000]
Steps Greater Than 8000: [ 8200  9000 10000  8500  9200 11000]


In [3]:
# 3 Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.

scores = np.array([180, 195, 210, 175, 225, 190, 205, 185])
selected_scores = scores[[1, 4, 6]]
print("All Match Scores:", scores)
print("Scores from Matches 2, 5, and 7:", selected_scores)

All Match Scores: [180 195 210 175 225 190 205 185]
Scores from Matches 2, 5, and 7: [195 225 205]


In [4]:
# 4 Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>

import numpy as np
prices = np.array([499, 999, 1499, 2499, 3999])

# Apply 10% discount using broadcasting
discounted_prices = prices * 0.90

print("Original Prices:", prices)
print("Discounted Prices:", discounted_prices)


Original Prices: [ 499  999 1499 2499 3999]
Discounted Prices: [ 449.1  899.1 1349.1 2249.1 3599.1]


In [ ]:
# 5 Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.
import numpy as np


ratings = np.array([5, -2, 3, 0, -1, 4, -3, 2])
# Set all negative ratings to 0 using boolean masking
ratings[ratings < 0] = 0

print("Updated Ratings:", ratings)

Updated Ratings: [5 0 3 0 0 4 0 2]
