In [ ]:
# 1 Create a Python script that loads a sample image (use any image of your favorite cricketer or celebrity), converts it to a NumPy array, and prints the array shape to demonstrate how images are represented for CNNs.


from PIL import Image
import numpy as np

# Load image
image = Image.open("image.avif")

# Convert image to NumPy array
image_array = np.array(image)

# Print information
print("Image Shape:", image_array.shape)
print("Data Type:", image_array.dtype)

# Display first pixel values
print("First Pixel:", image_array[0, 0])

Image Shape: (821, 1460, 3)
Data Type: uint8
First Pixel: [29 25 30]


In [2]:
# 2 Implement a simple 2D convolution operation in Python using NumPy: given a 5x5 grayscale image array and a 3x3 filter, compute the output feature map without using any deep learning libraries.<br><br><em><strong>Hint:</strong> Use nested loops to slide the filter over the image and sum the element-wise products.</em>

# 5x5 image
img = np.array([
    [1, 2, 3, 0, 1],
    [4, 5, 6, 1, 0],
    [7, 8, 9, 2, 1],
    [1, 2, 3, 4, 5],
    [0, 1, 2, 3, 4]
])

# 3x3 filter
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

output = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        output[i, j] = np.sum(img[i:i+3, j:j+3] * kernel)

print(output)

[[-6. 12. 16.]
 [-6.  8. 12.]
 [-6.  2.  4.]]


3 Draw the architecture diagram of a basic CNN (on paper or using a tool like draw.io) showing input layer, one convolutional layer, one pooling layer, and an output layer. Label each part and briefly describe its function in 1-2 lines.



1. Input Layer
2. Convolution Layer
3. Pooling Layer
4. Output Layer

In [3]:
# 4 Write a function in Python that takes an image array and returns a new array where each pixel is replaced by the maximum value in its 2x2 local neighborhood (simulate max pooling).<br><br><em><strong>Constraint:</strong> Do not use any deep learning libraries like TensorFlow or PyTorch for this task.</em>

def max_pool(img):
    h, w = img.shape
    return img.reshape(h//2, 2, w//2, 2).max(axis=(1, 3))

# Example
image = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 8, 3, 1],
    [0, 2, 9, 4]
])

print(max_pool(image))


[[6 4]
 [8 9]]


5 Explain with a real-world example from Instagram or Zomato how translation invariance in CNNs is useful. Write 2-3 sentences connecting it to how these apps recognize faces or food items even if they appear in different positions in the image.

Instagram Example:
Instagram can recognize a person's face whether it appears in the center, corner, or side of a photo. CNNs use translation invariance so the same facial features can be detected even when the face changes position in the image.

Zomato Example:
When users upload food photos, Zomato can identify items like pizza or burgers even if they are placed at different locations in the picture. CNNs learn the food's features, allowing recognition regardless of where the item appears in the image.