In [1]:
# 1 Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.


import numpy as np

# Daily step counts for two friends (7 days)
friend1 = np.array([8000, 9500, 7000, 10000, 8500, 12000, 9000])
friend2 = np.array([7500, 9000, 8000, 9500, 9000, 11000, 8500])

# Element-wise operations
addition = friend1 + friend2
subtraction = friend1 - friend2
multiplication = friend1 * friend2
division = friend1 / friend2

print("Friend 1 Steps:", friend1)
print("Friend 2 Steps:", friend2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

print("\nDivision:")
print(division)

Friend 1 Steps: [ 8000  9500  7000 10000  8500 12000  9000]
Friend 2 Steps: [ 7500  9000  8000  9500  9000 11000  8500]

Addition:
[15500 18500 15000 19500 17500 23000 17500]

Subtraction:
[  500   500 -1000   500  -500  1000   500]

Multiplication:
[ 60000000  85500000  56000000  95000000  76500000 132000000  76500000]

Division:
[1.06666667 1.05555556 0.875      1.05263158 0.94444444 1.09090909
 1.05882353]


In [2]:
# 2 Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.

user_preferences = np.array([
    [5, 3, 1],
    [4, 2, 3],
    [1, 5, 4]
])
song_popularity = np.array([
    [2, 1, 3],
    [4, 2, 1],
    [3, 5, 2]
])
recommendations_dot = np.dot(user_preferences, song_popularity)
recommendations_matmul = np.matmul(user_preferences, song_popularity)
print("Recommendation Matrix using dot():")
print(recommendations_dot)
print("\nRecommendation Matrix using matmul():")
print(recommendations_matmul)

Recommendation Matrix using dot():
[[25 16 20]
 [25 23 20]
 [34 31 16]]

Recommendation Matrix using matmul():
[[25 16 20]
 [25 23 20]
 [34 31 16]]


In [ ]:
# 3 Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.

image = np.array([
    [120, 150, 180, 200],
    [100, 130, 160, 190],
    [ 80, 110, 140, 170],
    [ 60,  90, 120, 150]
])
print("Original Image:")
print(image)
rotated_image = image.T
print("\nTransposed (Rotated) Image:")
print(rotated_image)
mean_value = np.mean(image)
median_value = np.median(image)
std_value = np.std(image)
var_value = np.var(image)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_value)
print("Variance:", var_value)

Original Image:
[[120 150 180 200]
 [100 130 160 190]
 [ 80 110 140 170]
 [ 60  90 120 150]]

Transposed (Rotated) Image:
[[120 100  80  60]
 [150 130 110  90]
 [180 160 140 120]
 [200 190 170 150]]

Mean: 134.375
Median: 135.0
Standard Deviation: 39.205986468905486
Variance: 1537.109375


In [ ]:
# 4 Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>


ratings_corr = np.array([
    [1.0, 0.3, 0.2],
    [0.3, 1.0, 0.4],
    [0.2, 0.4, 1.0]
])

print("Correlation Matrix:")
print(ratings_corr)

# Determinant
det = np.linalg.det(ratings_corr)
print("\nDeterminant:")
print(det)

# Inverse (only if determinant is not zero)
inv = np.linalg.inv(ratings_corr)
print("\nInverse Matrix:")
print(inv)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(ratings_corr)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Correlation Matrix:
[[1.  0.3 0.2]
 [0.3 1.  0.4]
 [0.2 0.4 1. ]]

Determinant:
0.758

Inverse Matrix:
[[ 1.10817942 -0.29023747 -0.1055409 ]
 [-0.29023747  1.26649077 -0.44854881]
 [-0.1055409  -0.44854881  1.2005277 ]]

Eigenvalues:
[1.60746736 0.8113209  0.58121174]

Eigenvectors:
[[ 0.50578521  0.82403773  0.25523155]
 [ 0.63457746 -0.15497893 -0.75716113]
 [ 0.58437383 -0.54492509  0.60130182]]


In [6]:
# 5 Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

import numpy as np


orders = np.array([
    [120, 135, 150, 140, 160, 170], 
    [100, 110, 125, 130, 145, 155]   
])

print("Original Array (2x6):")
print(orders)

# Reshape to (3, 4)
reshaped = orders.reshape(3, 4)
print("\nReshaped Array (3x4):")
print(reshaped)

# Flatten the array
flattened = reshaped.flatten()
print("\nFlattened Array:")
print(flattened)

# Split into two equal parts
part1, part2 = np.split(flattened, 2)
print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

# Stack both parts vertically
stacked = np.vstack((part1, part2))
print("\nVertically Stacked Array:")
print(stacked)


Original Array (2x6):
[[120 135 150 140 160 170]
 [100 110 125 130 145 155]]

Reshaped Array (3x4):
[[120 135 150 140]
 [160 170 100 110]
 [125 130 145 155]]

Flattened Array:
[120 135 150 140 160 170 100 110 125 130 145 155]

Part 1:
[120 135 150 140 160 170]

Part 2:
[100 110 125 130 145 155]

Vertically Stacked Array:
[[120 135 150 140 160 170]
 [100 110 125 130 145 155]]
